name: download profile


on:
  workflow_dispatch

jobs:
 download:
  runs_on: ubuntu-latest

  steps:
  - name: Checkout
    uses: actions/checkout@v4.1.7

  steps:
  - name: download
    uses: echo "download image"



 
